require('dotenv').config();

const express = require('express');
const cors = require('cors');
const connectDB = require('./config/db');

const app = express();

/**
 * Allowed frontend origins
 * - Local development URLs
 * - Your Vercel production URL
 * - Any preview deployments generated by Vercel
 * - Additional URLs from FRONTEND_URL environment variable (comma-separated)
 */
const configuredOrigins = String(process.env.FRONTEND_URL || '')
  .split(',')
  .map((origin) => origin.trim())
  .filter(Boolean);

const allowedOrigins = new Set([
  'http://localhost:5173',
  'http://localhost:3000',
  'https://ai-movie-recomendation-system.vercel.app',
  'https://ai-movie-recommendation-system.vercel.app',
  ...configuredOrigins,
]);

const allowedOriginPatterns = [
  /^https:\/\/ai-movie-recomendation-system(?:-[a-z0-9-]+)?\.vercel\.app$/i,
  /^https:\/\/ai-movie-recommendation-system(?:-[a-z0-9-]+)?\.vercel\.app$/i,
];

/**
 * CORS Configuration
 */
const corsOptions = {
  origin(origin, callback) {
    // Allow requests without an Origin header
    // (Postman, curl, server-to-server requests, Hugging Face health checks)
    if (!origin) {
      return callback(null, true);
    }

    // Exact matches
    if (allowedOrigins.has(origin)) {
      return callback(null, true);
    }

    // Vercel preview deployments
    if (allowedOriginPatterns.some((pattern) => pattern.test(origin))) {
      return callback(null, true);
    }

    // Reject unknown origins
    return callback(new Error(`Origin ${origin} is not allowed by CORS`));
  },
  credentials: true,
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization'],
  optionsSuccessStatus: 204,
};

/**
 * Required for proper caching when CORS varies by Origin
 */
app.use((req, res, next) => {
  if (req.headers.origin) {
    res.header('Vary', 'Origin');
  }
  next();
});

/**
 * Important for Hugging Face Docker deployment:
 * trust proxy helps Express work correctly behind the platform's reverse proxy.
 */
app.set('trust proxy', 1);

/**
 * Middleware
 */
app.use(cors(corsOptions));
app.options(/.*/, cors(corsOptions));

app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: false }));

/**
 * Root route (useful to verify deployment)
 */
app.get('/', (req, res) => {
  res.status(200).json({
    message: 'AI Movie Recommendation Backend is running successfully 🚀',
  });
});

/**
 * Health check route
 * Hugging Face can use this to verify the container is healthy.
 */
app.get('/api/health', (req, res) => {
  res.status(200).json({
    ok: true,
    status: 'healthy',
    timestamp: new Date().toISOString(),
  });
});

/**
 * API Routes
 */
app.use('/api/auth', require('./routes/authRoutes'));
app.use('/api/movies', require('./routes/movieRoutes'));
app.use('/api/ai', require('./routes/aiRoutes'));
app.use('/api/ml', require('./routes/mlRoutes'));
app.use('/api/watchlist', require('./routes/watchlistRoutes'));

/**
 * 404 Handler
 */
app.use((req, res) => {
  res.status(404).json({
    message: 'Route not found',
    path: req.originalUrl,
  });
});

/**
 * Global Error Handler
 */
app.use((err, req, res, next) => {
  console.error('Error:', err.stack);

  // CORS-specific errors
  if (err.message && err.message.includes('not allowed by CORS')) {
    return res.status(403).json({
      message: err.message,
    });
  }

  res.status(500).json({
    message: 'Server Error',
    error:
      process.env.NODE_ENV === 'production'
        ? undefined
        : err.message,
  });
});

/**
 * Hugging Face uses PORT=7860 automatically.
 * Local development will use PORT from .env or default to 5001.
 */
const PORT = process.env.PORT || 7860;

/**
 * Start server after MongoDB connection
 */
const startServer = async () => {
  try {
    await connectDB();

    app.listen(PORT, '0.0.0.0', () => {
      console.log(`🚀 Server running on port ${PORT}`);
      console.log(`🌐 Environment: ${process.env.NODE_ENV || 'development'}`);
    });
  } catch (error) {
    console.error('❌ Server failed to start:', error.message);
    process.exit(1);
  }
};

startServer();